"""add oauth provider fields to user

Revision ID: 56ced40f3fa3
Revises: ffa7d372b27b
Create Date: 2025-11-11 18:28:30.267671

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '56ced40f3fa3'
down_revision = 'ffa7d372b27b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    auth_provider_enum = sa.Enum('LOCAL', 'GOOGLE', name='authprovider')
    auth_provider_enum.create(bind, checkfirst=True)

    op.alter_column('email_verification_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.add_column('users', sa.Column('provider', auth_provider_enum, nullable=False))
    op.add_column('users', sa.Column('provider_user_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=255),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_users_provider_user_id'), 'users', ['provider_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    auth_provider_enum = sa.Enum('LOCAL', 'GOOGLE', name='authprovider')

    op.drop_index(op.f('ix_users_provider_user_id'), table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=255),
               nullable=False)
    op.drop_column('users', 'provider_user_id')
    op.drop_column('users', 'provider')
    op.alter_column('refresh_tokens', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('email_verification_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    auth_provider_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
